triggers:
- envs: []
  last_enabled_at: 2024-02-08 20:49:29.500114
  name: daily_at_5am_utc
  pipeline_uuid: green_taxi_etl
  schedule_interval: 0 5 * * *
  schedule_type: time
  settings:
    landing_time_enabled: false
  sla: null
  start_time: 2024-02-08 20:38:00
  status: active
  variables: {}
